### ISSUE TITLE
Implement analytics tab

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/datadictionary#13]
- [x] Implement design described in excel
- [x] Look group name
- [x] Make sqlview id configurable in settings
- [ ] Prototype a d3 view (optional)

api/dashboards
api/dashboards/id.json: name,user,dashboardItems.length, created, groups[name], groups[access]

**Comment by josemp10** [comment]
We need to add a filter seach input field (we have aroung 580 dashboards). I have used jQuery datatables in the past, and they have a very simple filtering feature. https://jquery-datatables-column-filter.googlecode.com/svn/trunk/default.html

The behaviour of the default filter (the one above the table, 'Search'), is enough. We dont need the others (filter by columns)

**Comment by adrianq** [comment]
@josemp10 Can I use itemCount instead of dashboardItems when querying a single dashboard like this: http://127.0.0.1:8080/dhis/api/dashboards/PeRJHa3GbsK.json?

**Comment by josemp10** [comment]
Yes! Good idea!
