### ISSUE TITLE
Add category elements as child nodes to date elements in d3 graph

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/datadictionary#34]

**Comment by adrianq** [comment]
@josemp10 will have a look at the api and let me know

**Comment by josemp10** [comment]
API call:

..../api/analytics.json?dimension=co&dimension=dx:f4evVUK5OHX&filter=ou:rP1W74RpNWF&filter=pe:LAST_12_MONTHS&displayProperty=SHORTNAME

f4evVUK5OHX: DataElement ID
rP1W74RpNWF: Org. Unit ID

**Comment by josemp10** [comment]
Sorry, my mistake. The API call is:

..../api/analytics.json?dimension=co&dimension=dx:f4evVUK5OHX&filter=ou:rP1W74RpNWF&filter=pe:LAST_12_MONTHS&aggregationType=COUNT&displayProperty=SHORTNAME

I forgot to add aggregationType=COUNT in the previous one.
