### ISSUE TITLE
Provide production db

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/datadictionary#4]
@josemp10 pinging the issue

**Comment by josemp10** [comment]
You can find the backup here https://drive.google.com/drive/folders/0B8KIRhh6kcl6SWQ0OGxLMHcwYTA/0By0qdNQWCbKNOG03UjVuUEJuQ28/0By0qdNQWCbKNfm9MajhNS2x4WDFlTzZHWXRjaVpiRWVnVGU3aFpRTlZJMEFaU0cyTGpkLU0/0B9L0E_5bA3AofkQ4ZVQySm44Um93VS1sODBJSVBSdU1kNTdIQnBBQTBoMEpoVnJlSWFtOG8?ltmpl=drive

It is dated on 22/04/2015. Will try to get otra más reciente

**Comment by josemp10** [comment]
The login (to get in DHIS2, not the database): aquintana / aQuintana2015
