### ISSUE TITLE
Improve summary

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/datadictionary#40]
It should be sth like:
Datasets | 45 (DataValues)
Events | 2 (Instance)
Tracker | 2 (Instance)

@josemp10 will shed some light about how to get the instances

**Comment by josemp10** [comment]
I think you already know about data values
- Events: API call

..../api/analytics/events/aggregate/X1NHBCBk1Mb.json?stage=jljp8u36CaU&dimension=pe:LAST_12_MONTHS&filter=ou:NxKJFhKFGbN&outputType=EVENT&displayProperty=SHORTNAME

X1NHBCBk1Mb: Program UID
jljp8u36CaU: Stage UID (events is 1to1 with stage)
NxKJFhKFGbN: Org Unit (Country) UID
- Tracker: In this case you need  to call the API bellow 'n' times, being 'n' the number of program stages.  You need to change the Stage UID for each API call, and adding the result to the total

(tracker is 1ton with stage)

How to get the stages: https://www-staging.psi-mis.org/api/programs/X1NHBCBk1Mb.json?fields=programStages
