### ISSUE TITLE
Storing the settings

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/datadictionary#49]
We may have a json (or xml) file somewhere in the directory tree where we store the settings of the app ('Organization Unit Level, 'SQL View Id'). So the app can retrieve the values from a there (like a config file)

**Comment by josemp10** [comment]
SQL View Id: dVMteD9Q0lU

**Comment by adrianq** [comment]
Closing this one as we are already taking care of this [here](https://github.com/EyeSeeTea/datadictionary/pull/70)
