### ISSUE TITLE
Dashboard tab improvements and bug fixing

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/datadictionary#65]
- [x] Check compatibility with 2.25/2.26. Versions below 2.25 are not allowed. Error message should be displayed for these versions.
- [x] Persist sqlViewIds as application metadata using DHIS API		
- [x] Persist Org Unit Level as application metadata using DHIS API
- [x] Improve settings look & feel
- [x] [Adrián] Fix link to Data Dictionary release notes on header and update release note.
- [x] Remove unused tabs (comment, dont' actually remove them)

**Comment by adrianq** [comment]
API to store information in DHIS2
https://docs.dhis2.org/2.25/en/developer/html/webapi_data_store.html

**Comment by tokland** [comment]
feature/65-update-to-225-persisted-settings

- Compatibility 2.25: Done. 2.25 made a breaking change in the relationships of dataElements/dataSetElements, for more info see https://lists.launchpad.net/dhis2-users/msg11754.html.  
- Alert window if DHIS version < 2.25: http://download.zaudera.com/public/65-version.png
- All settings persisted (no save button,  on-the-fly on input changes)
- Look & feel: http://download.zaudera.com/public/65-settings.png
-  Remove unused tabs: I've hidden it with CSS.
- Search was broken in "DataSets & Programs" tab, fixed.

**Comment by adrianq** [comment]
@tokland My task in this card is done. We will update the release notes when we know exactly what goes in this release. I have updated #68 with this task so we don't forget about it.

**Comment by tokland** [comment]
Cool, moving to "To test" then.
