### ISSUE TITLE
Column schema

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/datadictionary#67]
- [x] ~~Modify tables popups (3x) to use DataTables Library with the plugins.~~ DataTables does not implement transposing, use the existing table.	
- [x] Implement save/load settings view functionality. Make tables listing dynamic (list and pop-up columns) depending on schema (load settings). These settings can be defined per 1) Datasets & Programs and Data Element Groups and 2) Indicator Groups.
- [x] Implement “Load Settings” popup.	
- [x] Implement “Editing Settings” panel: layout and features.
- [x] Create buttons to save current status as user settings or organisational settings (if user has permissions). Implement cancel button.
- [x] Implement “Load Settings” and “Edit Settings” links accordingly to user permissions.
- [x] Persist user preference per table. How the user wants to see the table (using either default settings or user setting or organisational settings). The last option loaded by the user will be used as the predefined one.	
- [x] Organisational and user settings will be created/persisted the first time the user tries to edit this preferences. It will not exist server side until that point in time. On init both of them will be duplicate of default settings.

**Comment by adrianq** [comment]
Mockups:
![listview](https://cloud.githubusercontent.com/assets/6850223/22876200/6191f62e-f1c7-11e6-8dd6-1458761475b0.png)
![listviewloadingsetting](https://cloud.githubusercontent.com/assets/6850223/22876213/6bf14ea8-f1c7-11e6-8cbe-ce664a917a18.png)
![listvieweditingsetting](https://cloud.githubusercontent.com/assets/6850223/22876219/72a27844-f1c7-11e6-885f-e870bc01f088.png)

**Comment by adrianq** [comment]
@tokland I am updating this card with the remaining tasks we identified during the meeting. Feel free to add/edit anything:
- [x] Cosmetics
  - [x] Visibility columns links under settings in popup
  - [x] Visibility columns links should not change width whether selected or not.
  - [x] Smaller Save/cancel texts in popup (0.8em)
  - [x] Add select all/none links to visibility columns.
  - [x] Wrap settings in listings (rounded)
  - [x] Wrap settings in popup
  - [x] Help in columns settings with hover. Help text more detailed.
  - [x] Title popup selection settings: "Visualization settings"
  - [x] organisation -> organization
- [x] Implement dynamics attributes
- [x] Implement (hack) synchronous load settings feature so that colorder works properly
- [x] Unify schema for datasets & programs and dataelements group
- [x] Test how new attributes will impact on colorder and evaluate/perform fix accordingly
- [x] Double check everything is working fine
- [x] Upload new branch with the feature. I have just checked the code is not in the repo and I got a bit nervous ;)

**Comment by adrianq** [comment]
btw @tokland it would be great if you can upload your branch before Wed so I can give it a try and ask you any question on our next meeting. Thanks!

**Comment by tokland** [comment]
There you go!  `[new branch]      feature/67-column-schema`

**Comment by tokland** [comment]
- New columns in colReorder: no problem, new columns are positioned at the end.
- Regarding the colOrder bug on async loading, I opened an issue. The author replied he's gonna look into it this week: https://github.com/DataTables/ColReorder/issues/62 For now, the workaround is working fine.

**Comment by tokland** [comment]
Some screenshots so you don't have to setup it up to see the changes. I've added a select ALL/NONE link.

![dd1](https://cloud.githubusercontent.com/assets/24643/23403896/9c40bb38-fdb2-11e6-89d2-9a11273a1f27.png)
![dd2](https://cloud.githubusercontent.com/assets/24643/23403897/9c4149b8-fdb2-11e6-8182-265ba39161f4.png)

**Comment by adrianq** [comment]
Thanks @tokland ! Awesome work! :)

**Comment by tokland** [comment]
Some details after today's review:

- [x] Ajax sync request does not run always function
- [x] _name_'s settings -> my settings
- [x] incorrect help message for listings (shows the message for popups)

**Comment by tokland** [comment]
@adrianq EyeSeeTea/datadictionary/pull/76 updated with last changes.
