### ISSUE TITLE
Test app with 2.26

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/datadictionary#75]
Last changes have been developed for 2.25, check that everything works with 2.26 (the client will use that version) and update the versioned API call.

**Comment by adrianq** [comment]
@tokland dev-jade.jhpiego.org has a DHIS 2.26. It seems to be working fine but it would be great if you can double-check it quickly. Also remember to update the app to allow 2.25, 2.26 and to use 2.26 for any greater version. I think you did it during our last meeting but just in case... Thanks!

**Comment by tokland** [comment]
https://github.com/EyeSeeTea/datadictionary/commits/feature/fixes-and-improvements

Works 25, 26.
