### ISSUE TITLE
Migrate to 2.30

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/datadictionary#86]
- [x] In dataset and programs, you can only choose datasets in both versions. Should the program be selected? Or maybe we need to change the section name. -> Change tab name

- [x] In the dashboard, dashboards are not displayed in 2.30.
-> Line 45 in analytics.js. SQLView structure has changed and now we have a response like response.listGrid.rows instead of response.rows. We should change this line:
'$.each(json_Data.rows, function(i_dashboard, item_dashboard) {' and the call to use paging=false when asking sqlview.

- [ ] In the org unit section the queries sometimes never end, maybe it depends more on the resources of the server than the version. -> *Could not reproduce in local server, probably a 500 for excessive server load.*

- [ ] In both versions, it sometimes shows a lower level (WHO regions sometimes show countries instead of regions) -> *I wasn't able to reproduce it (do we have an example?)*

**Comment by tokland** [comment]
- [x] Added reporting-rate-metric, required for dx dimension of types dataset. Example: `dimension=dx:lyLU2wR22tC` -> `dimension=dx:lyLU2wR22tC.REPORTING_RATE`.

https://docs.dhis2.org/2.30/en/developer/html/dhis2_developer_manual_full.html
